export const ACTION_LOAD_COURSES = 'LOAD_COURSES'
export const ACTION_COURSE_ADD= 'COURSE_ADD'
export const ACTION_COURSE_REMOVE = 'COURSE_REMOVE'
export const ACTION_COURSE_UPDATE = 'COURSE_UPDATE'
export const ACTION_COURSE_STUDENT_REMOVE= 'COURSE_STUDENT_REMOVE'
export const ACTION_COURSE_STUDENT_ADD = 'COURSE_STUDENT_ADD'
export const ACTION_COURSE_ADD_CLASS = 'COURSE_ADD_CLASS'
export const ACTION_COURSE_REMOVE_CLASS = 'COURSE_REMOVE_CLASS'

// STUDENT
export const ACTION_LOAD_STUDENTS = 'LOAD_STUDENTS'
export const ACTION_STUDENT_ADD = 'ADD_STUDENT'
export const ACTION_STUDENT_REMOVE = 'REMOVE_STUDENT'
export const ACTION_STUDENT_UPDATE = 'UPDATE_STUDENT'

// CLASSES
export const ACTION_CLASS_ADD = 'ADD_CLASS'
export const ACTION_CLASS_LOADS = 'LOAD_CLASSES'
export const ACTION_CLASS_REMOVE = 'REMOVE_CLASS'
